language: php

php:
  - 5.6
  - 7.0
  - 8.0

sudo: false

cache:
  directories:
    - laravel
install:
  # specify the laravel service providers to insert
  - export PACKAGE_PROVIDER="
    veerenjp\\\\RestAPI\\\\Providers\\\\ApiServiceProvider::class"
  - export FACADES="
    'ApiRoute' => veerenjp\\\\RestAPI\\\\Facades\\\\ApiRoute::class"
  - export DB_HOST="localhost"
  - export DB_DATABASE="homestead_test"
  - export DB_USERNAME="root"
  - export DB_PASSWORD=""
  #specify the package to test
  - export PACKAGE_NAME=veerenjp/laravel-rest-api
  #run the setup script
  - mysql -e 'create database homestead_test;'

services: mysql

script:
  - cd laravel/laravel-rest-api
  - ../vendor/bin/phpunit
